version: '3.9'

services:
    server:
        container_name: contacts-api
        build:
            context: .
        restart: always
        environment:
            NODE_ENV: production
            SESSION_SECRET: ${SESSION_SECRET}
            PORT: ${PORT}
            DB_URL_PROD: ${DB_URL_PROD}
            DB_URL_DEV: ${DB_URL_DEV}
            URL_CLIENT: ${URL_CLIENT}
            EMAIL_HOST: ${EMAIL_HOST}
            EMAIL_PORT: ${EMAIL_PORT}
            EMAIL_AUTH_USER: ${EMAIL_AUTH_USER}
            EMAIL_AUTH_PASS: ${EMAIL_AUTH_PASS}
            EMAIL_SECURE: ${EMAIL_SECURE}
            EMAIL_REJECT_UNAUTHORIZED: ${EMAIL_REJECT_UNAUTHORIZED}
            GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        ports:
            - 4000:4000
    db:
        container_name: contacts-db
        image: mongo:5
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGODB_DATABASE: contacts-db
        volumes:
            - ./data:/data/db
