version: '3.9'

services:
    api:
        container_name: 'contacts-api'
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            NODE_ENV: ${ENV}
            SESSION_SECRET: ${SESSION_SECRET}
            PORT: ${PORT}
            DB_URL_PROD: ${DB_URL_PROD}
            DB_URL_DEV: ${DB_URL_DEV}
            URL_CLIENT: ${URL_CLIENT}
            EMAIL_HOST: ${EMAIL_HOST}
            EMAIL_PORT: ${EMAIL_PORT}
            EMAIL_AUTH_USER: ${EMAIL_AUTH_USER}
            EMAIL_AUTH_PASS: ${EMAIL_AUTH_PASS}
            EMAIL_SECURE: ${EMAIL_SECURE}
            EMAIL_REJECT_UNAUTHORIZED: ${EMAIL_REJECT_UNAUTHORIZED}
            GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        ports:
            - 4000:4000
            - 9229:9229
        volumes:
            - ./src:/usr/src/app/src
        depends_on:
            - db

    db:
        container_name: 'contacts-db'
        image: mongo:5
        restart: always
        volumes:
            - ./data:/data/db
        environment:
            MONGODB_DATABASE: contacts-db
        ports:
            - 27017:27017
volumes:
    data:
