version: '3.9'

services:
    db:
        container_name: contacts-db
        image: mongo:5
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGODB_DATABASE: contacts-db
        volumes:
            - ../data:/data/db
